version: '3'

services:
  parler-search:
    build: .
    ports:
      - 5005:5000
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis
    expose:
      - 6379
