FROM python:3.9-slim

ENV QUART_ENV=development
ENV QUART_DEBUG=1

COPY requirements.txt /app/requirements.txt
COPY requirements-dev.txt /app/requirements-dev.txt

WORKDIR /app

RUN pip install -r requirements-dev.txt

COPY src/ /app
COPY tests/ /app/tests
COPY pytest.ini /app/pytest.ini

CMD ["hypercorn", "--bind=0.0.0.0:5000", "app:app"]
