version: '3'

services:
  redis:
    image: redis
    expose:
      - 6379

  parler-search:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - 5005:5000
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
