name: Lint and Test

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pre-commit checks
        run: pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pytest
        run: ./bin/test.sh
        env:
          MONGO_USER: user
          MONGO_PASS: pass
          MONGO_ENDPOINT: localhost
          MONGO_PORT: 1312
          PYTHONPATH: src
