name: Lint and Test

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install
      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest
        env:
          MONGO_USER: user
          MONGO_PASS: pass
          MONGO_ENDPOINT: localhost
          MONGO_PORT: 1312
